import { useEffect, useMemo, useRef, useState } from "react";
import maharashtraLogo from "./assets/maharashtra-logo.png";
import ApplicationSetup from "./ApplicationSetup";
import ApprovalRoadmap from "./ApprovalRoadmap";
import {
  IconHome,
  IconFileText,
  IconRoadmap,
  IconBot,
  IconFileCheck,
  IconClockAlert,
  IconRepeat,
  IconAward,
  IconBell,
  IconUser,
  IconBuilding,
  IconCheck,
  IconArrowRight,
  IconSearch,
  IconAlertTriangle,
  IconInfo,
  IconPlus,
  IconShieldCheck
} from "./Icons";

/* ============================================================
   HELPER: Derive display name + initials from user prop
   ============================================================ */
function getUserDisplayName(user) {
  if (!user) return "Business User";
  return (
    user.name ||
    user.full_name ||
    user.username ||
    (user.email ? user.email.split("@")[0] : null) ||
    "Business User"
  );
}

function getUserInitial(user) {
  const name = getUserDisplayName(user);
  return name.charAt(0).toUpperCase();
}

function getUserEmail(user) {
  return user?.email || "—";
}

/* ============================================================
   HELPER: Greeting based on hour
   ============================================================ */
function getGreeting() {
  const h = new Date().getHours();
  if (h < 12) return "Good morning";
  if (h < 17) return "Good afternoon";
  return "Good evening";
}

/* ============================================================
   AI ASSISTANT — Client-side keyword matching
   Contextual to UdyogFlow / MAITRI / Maharashtra industrial approvals.
   Does NOT claim to be an LLM or a live AI service.
   ============================================================ */
const SUGGESTED_QUESTIONS = [
  "What approvals are required for my business?",
  "What documents should I prepare?",
  "Which department handles this approval?",
  "What should I complete next?",
  "How can I track my application?",
];

function getBotResponse(input, applications) {
  const q = input.toLowerCase().trim();
  const hasApps = applications && applications.length > 0;
  const firstApp = hasApps ? applications[0] : null;

  // ── Approvals required ──
  if (
    q.includes("approval") ||
    q.includes("required") ||
    q.includes("clearance") ||
    q.includes("license") ||
    q.includes("permit") ||
    q.includes("what do i need")
  ) {
    if (firstApp) {
      return {
        text: `Based on your registered application for **${firstApp.business_name}** (${firstApp.industry} sector, ${firstApp.location}), the typical clearances include:`,
        list: [
          "MPCB Consent to Establish (CTE) — environmental clearance",
          "MIDC Land Allotment & Building Plan Approval",
          "Factory License under Factories Act, 1948 (DISH)",
          "Fire NOC from Maharashtra Fire Services",
          "Udyam / MSME Registration (if applicable)",
        ],
        action: "roadmap",
        note: "Open your Approval Roadmap for the exact sequenced list generated by the MAITRI engine for your sector and location.",
      };
    }
    return {
      text: "The approvals required depend on your industry sector, location, and enterprise size. Common clearances for Maharashtra include:",
      list: [
        "MPCB Consent to Establish (CTE) — pollution control",
        "MIDC Land Allotment & Water Connection",
        "Factory License (DISH) — Factories Act, 1948",
        "Fire Services NOC",
        "Udyam MSME Registration",
      ],
      action: "application",
      note: "Start a New Application to generate a personalized roadmap via the MAITRI Clearance Engine.",
    };
  }

  // ── Documents ──
  if (
    q.includes("document") ||
    q.includes("form") ||
    q.includes("certificate") ||
    q.includes("prepare") ||
    q.includes("checklist") ||
    q.includes("upload")
  ) {
    return {
      text: "Standard documents required for most Maharashtra industrial clearances:",
      list: [
        "Company Incorporation Certificate (MCA / ROC)",
        "Udyam Registration Certificate",
        "MIDC Land Allotment Order / 7/12 Extract",
        "Site Plan, Layout, and Process Flow Diagram",
        "Environmental Impact details (for Red / Orange category)",
        "Project Report with investment, employment, and water/power load",
      ],
      note: "Pre-validate these in the Documents section before filing. Verified documents can be reused across departments.",
    };
  }

  // ── Department / MPCB ──
  if (
    q.includes("mpcb") ||
    q.includes("pollution") ||
    q.includes("environment") ||
    q.includes("consent")
  ) {
    return {
      text: "The Maharashtra Pollution Control Board (MPCB) handles environmental clearances.",
      list: [
        "Consent to Establish (CTE) — before construction / installation",
        "Consent to Operate (CTO) — before commencement of production",
        "Industries are classified as Red, Orange, Green, or White category",
        "SLA: 45 days under Maharashtra Right to Public Services Act",
      ],
      note: "Helpline: 1800-233-5555 | Portal: mpcb.gov.in",
    };
  }

  // ── Department / MIDC ──
  if (q.includes("midc") || q.includes("land") || q.includes("plot") || q.includes("infrastructure")) {
    return {
      text: "MIDC (Maharashtra Industrial Development Corporation) handles land allotment and infrastructure.",
      list: [
        "Plot allotment within designated industrial estates",
        "Building plan approval and commencement certificate",
        "Water & power connection within MIDC zones",
        "SLA: 21 days for standard allotment processing",
      ],
      note: "Portal: midcindia.org | This clearance is often processed in parallel with MPCB CTE.",
    };
  }

  // ── Department / DISH / Factory ──
  if (
    q.includes("dish") ||
    q.includes("factory") ||
    q.includes("safety") ||
    q.includes("factories act")
  ) {
    return {
      text: "The Directorate of Industrial Safety and Health (DISH) issues factory licenses.",
      list: [
        "Factory Plan Approval — submit site plan and machinery layout",
        "Factory License under Factories Act, 1948",
        "Renewal is annual; submit by April 30 each year",
        "SLA: 30 days for new factory license",
      ],
      note: "DISH requires a certified factory inspector site visit for manufacturing units.",
    };
  }

  // ── Department / Fire ──
  if (q.includes("fire") || q.includes("noc") || q.includes("fire services")) {
    return {
      text: "Maharashtra Fire Services issues the Fire NOC.",
      list: [
        "Submit fire safety plan along with building plan",
        "Sprinkler, extinguisher, and exit clearances required",
        "Annual Fire Safety Audit (Form B) — due 30 June",
        "Processing time: 15–30 days",
      ],
      note: "Fire NOC is typically processed in the pre-operation stage alongside the factory license.",
    };
  }

  // ── Which department ──
  if (q.includes("which department") || q.includes("department") || q.includes("who handles") || q.includes("authority")) {
    return {
      text: "Key departments involved in Maharashtra industrial approvals:",
      list: [
        "MPCB — Pollution & environmental clearances",
        "MIDC — Land allotment & industrial infrastructure",
        "DISH — Factory licensing & industrial safety",
        "Maharashtra Fire Services — Fire NOC",
        "Revenue / Collector's Office — Land use conversion",
        "Electricity Board (MSEDCL / Mahavitaran) — Power connections",
      ],
      action: "roadmap",
      note: "Your Approval Roadmap shows exactly which department handles each step for your sector.",
    };
  }

  // ── What to complete next / status ──
  if (
    q.includes("next") ||
    q.includes("complete") ||
    q.includes("pending") ||
    q.includes("status") ||
    q.includes("what should i do") ||
    q.includes("step")
  ) {
    if (firstApp) {
      return {
        text: `Your application **${firstApp.business_name}** is currently: **${firstApp.status || "Draft"}**.`,
        list:
          (firstApp.status || "").toLowerCase() === "draft"
            ? [
                "Submit your application to proceed to MAITRI review",
                "Ensure all mandatory fields are complete",
                "Upload Company Incorporation Certificate and Site Plan",
              ]
            : [
                "Open your Approval Roadmap to see pending clearances",
                "Check the Delay Alerts panel for SLA warnings",
                "Verify document uploads for departments under review",
              ],
        action: "roadmap",
        note: "View your Approval Roadmap for the full step-by-step sequence.",
      };
    }
    return {
      text: "You haven't created an application yet. Here's how to start:",
      list: [
        "Click 'New Application' to register your enterprise",
        "Enter your business name, industry, location, and description",
        "The MAITRI engine will generate your statutory clearance roadmap",
      ],
      action: "application",
      note: "The entire process is digital and guided — no visits to government offices needed for the initial stage.",
    };
  }

  // ── Track application ──
  if (
    q.includes("track") ||
    q.includes("monitor") ||
    q.includes("progress") ||
    q.includes("check") ||
    q.includes("update")
  ) {
    return {
      text: "You can track your application progress in two ways:",
      list: [
        "Applications panel → see live status from the PostgreSQL database",
        "Approval Roadmap → detailed per-clearance status with SLA countdown",
        "Delay Alerts → proactive warnings if a department exceeds SLA",
        "Notifications → official circulars and status changes from MAITRI",
      ],
      action: "roadmap",
      note: "Status is updated by the backend as departments process your files.",
    };
  }

  // ── SLA / timeline / how long ──
  if (
    q.includes("sla") ||
    q.includes("how long") ||
    q.includes("timeline") ||
    q.includes("days") ||
    q.includes("time")
  ) {
    return {
      text: "Statutory SLA timelines under Maharashtra Right to Public Services Act:",
      list: [
        "MPCB CTE (Orange/Green): 45 days",
        "MPCB CTE (Red category): 60 days",
        "MIDC Plot Allotment: 21 days",
        "Factory License (DISH): 30 days",
        "Fire NOC: 15 days",
        "Udyam Registration: Instant (self-certification)",
      ],
      note: "Delays beyond SLA are reportable under the Right to Public Services Act. The Delay Alerts module monitors this for you.",
    };
  }

  // ── PSI / schemes / subsidy / incentive ──
  if (
    q.includes("psi") ||
    q.includes("scheme") ||
    q.includes("subsidy") ||
    q.includes("incentive") ||
    q.includes("benefit")
  ) {
    return {
      text: "Maharashtra Package Scheme of Incentives (PSI 2019) key benefits:",
      list: [
        "Industrial Promotion Subsidy: up to 100% of Fixed Capital Investment (D+/D zones)",
        "Interest Subsidy: 5% on term loans for MSMEs",
        "Electricity Duty Exemption: up to 10 years",
        "Stamp Duty Exemption for MIDC land",
        "MSInS Startup Patent Subsidy: up to ₹15 Lakhs",
      ],
      note: "Check eligibility in the Government Schemes section. Benefits vary by taluka classification (A, B, C, D, D+).",
    };
  }

  // ── Greeting / hello ──
  if (
    q.includes("hello") ||
    q.includes("hi") ||
    q.includes("namaskar") ||
    q.includes("namaste") ||
    q === "hey"
  ) {
    return {
      text: `Hello! I'm the UdyogFlow Assistant — here to help with industrial approvals, documents, departments, and government schemes.${hasApps ? ` I can see you have ${applications.length} registered application(s).` : ""}`,
      list: null,
      note: "Ask me about approvals, documents, departments, SLA timelines, or government schemes.",
    };
  }

  // ── Default fallback ──
  return {
    text: "I can help you with information about:",
    list: [
      "Required approvals & statutory clearances",
      "Document checklists for each department",
      "MPCB, MIDC, DISH and Fire Services procedures",
      "SLA timelines and delay prevention",
      "Government schemes & PSI 2019 incentives",
    ],
    note: "Try one of the suggested questions on the right, or ask about a specific department or clearance.",
  };
}

/* ============================================================
   COMPLIANCE CALENDAR HELPERS
   ============================================================ */
const COMPLIANCE_DEADLINES = [
  { day: 31, month: 2, label: "MPCB Form V (Environmental Statement)", type: "urgent" },
  { day: 30, month: 3, label: "Factory License Renewal (DISH)", type: "upcoming" },
  { day: 30, month: 5, label: "Annual Fire Safety Audit (Form B)", type: "scheduled" },
  { day: 30, month: 8, label: "MPCB Half-Yearly Return", type: "scheduled" },
  { day: 31, month: 11, label: "Factory Annual Report Filing", type: "upcoming" },
];

const MONTH_NAMES = [
  "January","February","March","April","May","June",
  "July","August","September","October","November","December",
];
const WEEKDAY_LABELS = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];

function buildCalendarDays(year, month) {
  const firstDay = new Date(year, month, 1).getDay();
  const daysInMonth = new Date(year, month + 1, 0).getDate();
  const today = new Date();
  const cells = [];

  for (let i = 0; i < firstDay; i++) {
    cells.push({ empty: true });
  }
  for (let d = 1; d <= daysInMonth; d++) {
    const isToday =
      today.getFullYear() === year &&
      today.getMonth() === month &&
      today.getDate() === d;
    const deadline = COMPLIANCE_DEADLINES.find(
      (dl) => dl.day === d && dl.month === month
    );
    cells.push({ day: d, isToday, deadline: deadline || null });
  }
  return cells;
}

/* ============================================================
   DOCUMENT PRE-VALIDATION — PROTOTYPE COMPONENT
   Uses React state only. No backend. No new npm packages.
   ============================================================ */
function DocumentPreValidation() {
  const [docs, setDocs] = useState([]);
  const [isDragOver, setIsDragOver] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [validating, setValidating] = useState(false);
  const fileInputRef = useRef(null);

  const formatSize = (bytes) => {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
  };

  const addFiles = (files) => {
    const newDocs = Array.from(files).map((file) => ({
      id: Date.now() + Math.random(),
      name: file.name,
      type: file.type || "application/octet-stream",
      size: file.size,
      status: "selected",
    }));
    setDocs((prev) => [...prev, ...newDocs]);
    setSubmitted(false);
  };

  const handleDrop = (e) => {
    e.preventDefault();
    setIsDragOver(false);
    const files = e.dataTransfer.files;
    if (files && files.length > 0) addFiles(files);
  };

  const handleDragOver = (e) => {
    e.preventDefault();
    setIsDragOver(true);
  };

  const handleDragLeave = () => setIsDragOver(false);

  const handleBrowse = () => {
    if (fileInputRef.current) fileInputRef.current.click();
  };

  const handleFileChange = (e) => {
    if (e.target.files && e.target.files.length > 0) {
      addFiles(e.target.files);
      e.target.value = "";
    }
  };

  const removeDoc = (id) => {
    setDocs((prev) => prev.filter((d) => d.id !== id));
    setSubmitted(false);
  };

  const handleSubmit = () => {
    if (docs.length === 0) return;
    setValidating(true);
    setTimeout(() => {
      setValidating(false);
      setSubmitted(true);
    }, 1200);
  };

  const getTypeLabel = (mimeType) => {
    if (mimeType.includes("pdf")) return "PDF";
    if (mimeType.includes("png")) return "PNG";
    if (mimeType.includes("jpeg") || mimeType.includes("jpg")) return "JPG";
    if (mimeType.includes("doc")) return "DOC";
    return mimeType.split("/")[1]?.toUpperCase() || "FILE";
  };

  const isSupportedType = (mimeType) => {
    return mimeType.includes("pdf") || mimeType.includes("jpeg") || mimeType.includes("jpg") || mimeType.includes("png");
  };

  return (
    <div className="module-view-container">
      <div className="module-header-banner">
        <div className="module-tag prototype">PRE-VALIDATION — PROTOTYPE</div>
        <h2>Document Pre-Validation</h2>
        <p>Upload documents to check file format and readiness before submission. No real upload occurs — this is a frontend prototype.</p>
      </div>

      <div className="doc-prevalidation-layout">
        {/* Upload Area */}
        <div className="doc-upload-section">
          <div
            className={`doc-dropzone${isDragOver ? " drag-over" : ""}`}
            onDrop={handleDrop}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onClick={handleBrowse}
            role="button"
            tabIndex={0}
            onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") handleBrowse(); }}
            aria-label="Click or drag files to upload"
          >
            <div className="dropzone-icon">📄</div>
            <p className="dropzone-primary">Drag &amp; drop your document here</p>
            <p className="dropzone-or">or</p>
            <button
              type="button"
              className="btn-browse-files"
              onClick={(e) => { e.stopPropagation(); handleBrowse(); }}
            >
              Browse Files
            </button>
            <p className="dropzone-support">Supported formats: PDF, JPG, PNG</p>
          </div>

          {/* Hidden file input */}
          <input
            ref={fileInputRef}
            type="file"
            multiple
            accept=".pdf,.jpg,.jpeg,.png"
            style={{ display: "none" }}
            onChange={handleFileChange}
          />

          {/* Add More button (only when docs exist) */}
          {docs.length > 0 && (
            <button
              type="button"
              className="btn-add-more-doc"
              onClick={handleBrowse}
            >
              + Add Document
            </button>
          )}
        </div>

        {/* Document List */}
        {docs.length > 0 && (
          <div className="doc-list-section">
            <h4 className="doc-list-title">Selected Documents ({docs.length})</h4>
            <div className="doc-items-list">
              {docs.map((doc) => (
                <div key={doc.id} className="doc-item-card">
                  <div className="doc-item-icon">
                    {doc.name.endsWith(".pdf") ? "📋" : doc.name.match(/\.(jpg|jpeg|png)$/i) ? "🖼️" : "📄"}
                  </div>
                  <div className="doc-item-info">
                    <strong className="doc-item-name">{doc.name}</strong>
                    <div className="doc-item-meta">
                      <span className="doc-meta-type">{getTypeLabel(doc.type)}</span>
                      <span className="doc-meta-size">{formatSize(doc.size)}</span>
                      {isSupportedType(doc.type) ? (
                        <span className="doc-meta-status ok">✓ Supported format</span>
                      ) : (
                        <span className="doc-meta-status warn">⚠ Unsupported type</span>
                      )}
                    </div>
                  </div>
                  <button
                    type="button"
                    className="doc-remove-btn"
                    onClick={() => removeDoc(doc.id)}
                    title="Remove document"
                    aria-label={`Remove ${doc.name}`}
                  >
                    ✕
                  </button>
                </div>
              ))}
            </div>

            {/* Submit Button */}
            {!submitted && (
              <button
                type="button"
                className="btn-submit-docs"
                onClick={handleSubmit}
                disabled={validating}
              >
                {validating ? (
                  <><span className="spinner-inline"></span>Validating…</>
                ) : (
                  "Submit Documents"
                )}
              </button>
            )}

            {/* Validation Result */}
            {submitted && (
              <div className="doc-validation-result">
                <div className="validation-success-header">
                  <span className="validation-check-icon">✓</span>
                  <h4>Documents submitted for pre-validation</h4>
                </div>
                <div className="validation-checks-list">
                  <div className="validation-check-item pass">
                    <span>✓</span>
                    <span>Document{docs.length > 1 ? "s" : ""} received ({docs.length} file{docs.length > 1 ? "s" : ""})</span>
                  </div>
                  <div className="validation-check-item pass">
                    <span>✓</span>
                    <span>File format{docs.every(d => isSupportedType(d.type)) ? " supported" : " — one or more files may need review"}</span>
                  </div>
                  <div className="validation-check-item pass">
                    <span>✓</span>
                    <span>Document{docs.length > 1 ? "s" : ""} ready for validation review</span>
                  </div>
                </div>
                <p className="validation-note">
                  In a live deployment, documents would be checked for resolution, digital signature, and content completeness. Verified documents can be reused across departments.
                </p>
                <button
                  type="button"
                  className="btn-add-more-doc"
                  style={{ marginTop: "16px" }}
                  onClick={() => { setSubmitted(false); setDocs([]); }}
                >
                  + Add More Documents
                </button>
              </div>
            )}
          </div>
        )}

        {/* Info box when empty */}
        {docs.length === 0 && (
          <div className="doc-empty-tip">
            <h4>What documents might you need?</h4>
            <ul>
              <li>Company Incorporation Certificate (MCA / ROC)</li>
              <li>Udyam Registration Certificate</li>
              <li>MIDC Land Allotment Order / 7/12 Extract</li>
              <li>Site Plan and Process Flow Diagram</li>
              <li>Environmental Impact Details (for Red / Orange category)</li>
              <li>Project Report with investment, employment, water/power load</li>
            </ul>
          </div>
        )}
      </div>
    </div>
  );
}

/* ============================================================
   MAIN COMPONENT
   ============================================================ */
function BusinessDashboard({ user, onLogout, onNavigateHome }) {
  // ── Navigation state ──
  const [activeView, setActiveView] = useState("dashboard");
  const [showApplication, setShowApplication] = useState(false);
  const [showRoadmap, setShowRoadmap] = useState(false);
  const [applicationData, setApplicationData] = useState(null);

  // ── Applications data (live PostgreSQL) ──
  const [applications, setApplications] = useState([]);
  const [loadingApplications, setLoadingApplications] = useState(true);
  const [tableSearch, setTableSearch] = useState("");
  const [tableStatusFilter, setTableStatusFilter] = useState("all");

  // ── Accessibility ──
  const [fontSizeLevel, setFontSizeLevel] = useState(1);

  // ── NEW: Sidebar collapse ──
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);

  // ── NEW: Live clock ──
  const [clockStr, setClockStr] = useState(() => {
    const now = new Date();
    return now.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" });
  });

  // ── NEW: KPI animated display values ──
  const [displayedStats, setDisplayedStats] = useState({
    total: 0, approved: 0, inProgress: 0, actionRequired: 0,
  });

  // ── NEW: AI Assistant chat state ──
  const [chatMessages, setChatMessages] = useState([
    {
      role: "bot",
      text: "Hello! I'm the UdyogFlow Assistant — a guided help tool for industrial approvals, documents, departments, timelines, and government schemes.",
      list: null,
      note: null,
      action: null,
    },
  ]);
  const [chatInput, setChatInput] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const chatEndRef = useRef(null);

  // ── NEW: Notifications read/unread state ──
  const INITIAL_NOTIFS = [
    { id: 1, type: "critical", icon: "⚠️", title: "MPCB Circular: Online Effluent Sensor Data", body: "Units generating over 50 KLD effluent must connect sensors by March 31, 2026.", time: "Today", read: false },
    { id: 2, type: "info", icon: "📢", title: "MAITRI Scheduled Maintenance Notice", body: "Database optimization on Sunday 02:00 AM to 04:00 AM IST.", time: "Yesterday", read: false },
    { id: 3, type: "success", icon: "✅", title: "Chakan Phase II Substation Energized", body: "Power load feasibility turnaround time reduced to 3 days for Chakan plots.", time: "3 days ago", read: false },
  ];
  const [notifications, setNotifications] = useState(INITIAL_NOTIFS);

  // ── NEW: Compliance calendar state ──
  const today = new Date();
  const [calYear, setCalYear] = useState(today.getFullYear());
  const [calMonth, setCalMonth] = useState(today.getMonth());

  // ── NEW: IntersectionObserver refs for fade-in ──
  const featureGridRef = useRef(null);
  const kpiRowRef = useRef(null);

  /* ----------------------------------------------------------
     Fetch applications (live PostgreSQL, strict user isolation)
  ---------------------------------------------------------- */
  const fetchApplications = async (showLoading = false) => {
    if (!user?.user_id) {
      setApplications([]);
      setLoadingApplications(false);
      return;
    }
    try {
      if (showLoading) {
        setLoadingApplications(true);
      }
      const response = await fetch(
        `https://udyogflow.onrender.com/api/applications?userId=${user.user_id}`
      );
      if (!response.ok) throw new Error("Failed to fetch applications");
      const data = await response.json();
      const userApps = Array.isArray(data)
        ? data.filter(
            (app) =>
              app &&
              app.user_id != null &&
              String(app.user_id) === String(user.user_id)
          )
        : [];
      setApplications(userApps);
    } catch (error) {
      console.error("Error fetching applications:", error);
      if (showLoading) {
        setApplications([]);
      }
    } finally {
      setLoadingApplications(false);
    }
  };

  useEffect(() => {
    if (user?.user_id) {
      fetchApplications(true);
    } else {
      setApplications([]);
      setLoadingApplications(false);
    }
  }, [user?.user_id]);

  /* ----------------------------------------------------------
     Handle newly created application (immediate update & sync)
  ---------------------------------------------------------- */
  const handleApplicationCreated = (newApplication) => {
    if (!newApplication) return;
    if (
      newApplication.user_id != null &&
      String(newApplication.user_id) === String(user?.user_id)
    ) {
      setApplications((prev) => {
        const exists = prev.some(
          (app) => app.application_id === newApplication.application_id
        );
        if (exists) return prev;
        return [newApplication, ...prev];
      });
    }
    fetchApplications(false);
  };

  /* ----------------------------------------------------------
     Live clock (NEW)
  ---------------------------------------------------------- */
  useEffect(() => {
    const timer = setInterval(() => {
      const now = new Date();
      setClockStr(
        now.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" })
      );
    }, 30000);
    return () => clearInterval(timer);
  }, []);

  /* ----------------------------------------------------------
     Compute statistics (existing — unmodified)
  ---------------------------------------------------------- */
  const statistics = useMemo(() => {
    const total = applications.length;
    const approved = applications.filter(
      (app) => (app.status || "").toLowerCase() === "approved"
    ).length;
    const inProgress = applications.filter((app) => {
      const s = (app.status || "").toLowerCase();
      return s === "in progress" || s === "in review" || s === "under review";
    }).length;
    const actionRequired = applications.filter(
      (app) => (app.status || "").toLowerCase() === "action required"
    ).length;
    const rejected = applications.filter((app) => {
      const s = (app.status || "").toLowerCase();
      return s === "rejected" || s === "returned";
    }).length;
    const draft = applications.filter(
      (app) => (app.status || "").toLowerCase() === "draft"
    ).length;
    return { total, approved, inProgress, actionRequired, rejected, draft };
  }, [applications]);

  /* ----------------------------------------------------------
     KPI count-up animation (NEW)
  ---------------------------------------------------------- */
  useEffect(() => {
    if (loadingApplications) return;
    const targets = {
      total: statistics.total,
      approved: statistics.approved,
      inProgress: statistics.inProgress,
      actionRequired: statistics.actionRequired,
    };
    if (targets.total === 0) {
      setDisplayedStats(targets);
      return;
    }
    let frame = 0;
    const totalFrames = 18;
    const interval = setInterval(() => {
      frame++;
      const progress = frame / totalFrames;
      const ease = 1 - Math.pow(1 - progress, 2);
      setDisplayedStats({
        total: Math.round(targets.total * ease),
        approved: Math.round(targets.approved * ease),
        inProgress: Math.round(targets.inProgress * ease),
        actionRequired: Math.round(targets.actionRequired * ease),
      });
      if (frame >= totalFrames) {
        setDisplayedStats(targets);
        clearInterval(interval);
      }
    }, 30);
    return () => clearInterval(interval);
  }, [loadingApplications, statistics]);

  /* ----------------------------------------------------------
     Donut chart (existing — unmodified)
  ---------------------------------------------------------- */
  const chartTotal = statistics.approved + statistics.inProgress + statistics.rejected;
  const approvedPercent = chartTotal > 0 ? (statistics.approved / chartTotal) * 100 : 0;
  const progressPercent = chartTotal > 0 ? (statistics.inProgress / chartTotal) * 100 : 0;
  const approvedEnd = approvedPercent;
  const progressEnd = approvedPercent + progressPercent;
  const donutBackground =
    chartTotal > 0
      ? `conic-gradient(#059669 0% ${approvedEnd}%, #d97706 ${approvedEnd}% ${progressEnd}%, #dc2626 ${progressEnd}% 100%)`
      : "#e2e8f0";

  /* ----------------------------------------------------------
     Filtered applications table (existing — unmodified)
  ---------------------------------------------------------- */
  const filteredApplications = useMemo(() => {
    return applications.filter((app) => {
      const query = tableSearch.toLowerCase();
      const matchesSearch =
        !query ||
        app.business_name?.toLowerCase().includes(query) ||
        app.industry?.toLowerCase().includes(query) ||
        app.location?.toLowerCase().includes(query) ||
        String(app.application_id).includes(query);
      if (!matchesSearch) return false;
      const st = (app.status || "Draft").toLowerCase();
      if (tableStatusFilter === "all") return true;
      if (tableStatusFilter === "approved") return st === "approved";
      if (tableStatusFilter === "in-progress")
        return st === "in progress" || st === "in review" || st === "under review";
      if (tableStatusFilter === "action-required") return st === "action required";
      if (tableStatusFilter === "draft") return st === "draft";
      return true;
    });
  }, [applications, tableSearch, tableStatusFilter]);

  /* ----------------------------------------------------------
     Open roadmap (existing — unmodified)
  ---------------------------------------------------------- */
  const openRoadmap = (application) => {
    if (!application) {
      alert("No application available.");
      return;
    }
    setApplicationData({
      applicationId: application.application_id,
      businessName: application.business_name,
      industry: application.industry,
      location: application.location,
      userId: user?.user_id,
    });
    setShowRoadmap(true);
  };

  /* ----------------------------------------------------------
     Font size toggle (existing — unmodified)
  ---------------------------------------------------------- */
  const handleFontSize = (level) => {
    setFontSizeLevel(level);
    const size = level === 0 ? "13px" : level === 1 ? "14px" : "15px";
    document.documentElement.style.fontSize = size;
  };

  /* ----------------------------------------------------------
     AI Assistant — send message (NEW)
  ---------------------------------------------------------- */
  const handleChatSend = () => {
    const input = chatInput.trim();
    if (!input) return;

    const userMsg = { role: "user", text: input, list: null, note: null, action: null };
    setChatMessages((prev) => [...prev, userMsg]);
    setChatInput("");
    setIsTyping(true);

    setTimeout(() => {
      const response = getBotResponse(input, applications);
      const botMsg = { role: "bot", ...response };
      setChatMessages((prev) => [...prev, botMsg]);
      setIsTyping(false);
    }, 700);
  };

  const handleSuggestedQuestion = (q) => {
    setChatInput(q);
    const userMsg = { role: "user", text: q, list: null, note: null, action: null };
    setChatMessages((prev) => [...prev, userMsg]);
    setIsTyping(true);
    setTimeout(() => {
      const response = getBotResponse(q, applications);
      const botMsg = { role: "bot", ...response };
      setChatMessages((prev) => [...prev, botMsg]);
      setIsTyping(false);
    }, 700);
  };

  // Auto-scroll chat
  useEffect(() => {
    if (chatEndRef.current) {
      chatEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [chatMessages, isTyping]);

  /* ----------------------------------------------------------
     Notifications — read/unread toggle (NEW)
  ---------------------------------------------------------- */
  const unreadCount = notifications.filter((n) => !n.read).length;

  const toggleNotifRead = (id) => {
    setNotifications((prev) =>
      prev.map((n) => (n.id === id ? { ...n, read: !n.read } : n))
    );
  };

  const markAllRead = () => {
    setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
  };

  /* ----------------------------------------------------------
     Compliance calendar (NEW)
  ---------------------------------------------------------- */
  const calDays = useMemo(
    () => buildCalendarDays(calYear, calMonth),
    [calYear, calMonth]
  );

  const prevCalMonth = () => {
    if (calMonth === 0) { setCalMonth(11); setCalYear((y) => y - 1); }
    else setCalMonth((m) => m - 1);
  };
  const nextCalMonth = () => {
    if (calMonth === 11) { setCalMonth(0); setCalYear((y) => y + 1); }
    else setCalMonth((m) => m + 1);
  };

  /* ----------------------------------------------------------
     IntersectionObserver fade-in (NEW)
  ---------------------------------------------------------- */
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add("is-visible");
          }
        });
      },
      { threshold: 0.1 }
    );
    const elements = document.querySelectorAll(".fade-in-section");
    elements.forEach((el) => observer.observe(el));
    return () => observer.disconnect();
  }, [activeView]);

  /* ----------------------------------------------------------
     User display values
  ---------------------------------------------------------- */
  const displayName = getUserDisplayName(user);
  const userInitial = getUserInitial(user);
  const userEmail = getUserEmail(user);

  /* ----------------------------------------------------------
     Sub-flow: New Application
  ---------------------------------------------------------- */
  if (showApplication) {
    return (
      <ApplicationSetup
        userId={user?.user_id}
        onBack={() => {
          setShowApplication(false);
          fetchApplications(false);
        }}
        onApplicationCreated={handleApplicationCreated}
        onGenerateRoadmap={(data) => {
          if (data?.application) {
            handleApplicationCreated(data.application);
          } else {
            fetchApplications(false);
          }
          setApplicationData(data);
          setShowApplication(false);
          setShowRoadmap(true);
        }}
      />
    );
  }

  /* ----------------------------------------------------------
     Sub-flow: Roadmap
  ---------------------------------------------------------- */
  if (showRoadmap) {
    return (
      <ApprovalRoadmap
        applicationData={applicationData}
        onBack={() => {
          setShowRoadmap(false);
          fetchApplications(false);
        }}
      />
    );
  }

  /* ----------------------------------------------------------
     RENDER
  ---------------------------------------------------------- */
  return (
    <div className="portal-layout">

      {/* ── 1. TOP GOVERNMENT HEADER ── */}
      <header className="gov-topbar">
        <div className="gov-topbar-inner">
          <div className="gov-topbar-brand">
            <img src={maharashtraLogo} alt="Government of Maharashtra" className="gov-logo-img" />
            <div className="gov-title-stack">
              <div className="gov-state-name">
                <strong>Government of Maharashtra</strong> · महाराष्ट्र शासन
              </div>
              <div className="gov-dept-name">Department of Industries · UdyogFlow Portal</div>
            </div>
          </div>

          <div className="gov-topbar-tools">
            {/* Font Resizer */}
            <div className="gov-accessibility">
              <span className="gov-tool-label">Text:</span>
              <button type="button" className={`tool-btn ${fontSizeLevel === 0 ? "active" : ""}`} onClick={() => handleFontSize(0)} title="Decrease font size">A-</button>
              <button type="button" className={`tool-btn ${fontSizeLevel === 1 ? "active" : ""}`} onClick={() => handleFontSize(1)} title="Default font size">A</button>
              <button type="button" className={`tool-btn ${fontSizeLevel === 2 ? "active" : ""}`} onClick={() => handleFontSize(2)} title="Increase font size">A+</button>
            </div>

            {/* Bell with dynamic unread count */}
            <button
              type="button"
              className="gov-bell-btn"
              onClick={() => setActiveView("notifications")}
              title="Notifications"
            >
              <IconBell size={18} />
              {unreadCount > 0 && (
                <span className="bell-badge">{unreadCount}</span>
              )}
            </button>

            {/* User chip with real name */}
            <button
              type="button"
              className="gov-user-chip"
              onClick={() => setActiveView("profile")}
              title="Your Profile"
            >
              <div className="user-avatar">{userInitial}</div>
              <div className="user-meta">
                <span className="user-name user-name-display">{displayName}</span>
                <span className="user-role">Maharashtra Investor</span>
              </div>
            </button>

            {(onLogout || onNavigateHome) && (
              <button type="button" className="gov-exit-btn" onClick={onLogout || onNavigateHome}>
                Sign Out
              </button>
            )}
          </div>
        </div>
      </header>

      {/* ── 2. BODY: SIDEBAR + MAIN ── */}
      <div className="portal-body-wrapper">

        {/* ── SIDEBAR ── */}
        <aside className={`portal-sidebar ${sidebarCollapsed ? "collapsed" : ""}`}>

          {/* Collapse toggle */}
          <div className="sidebar-collapse-btn">
            <button
              type="button"
              className="sidebar-toggle-icon"
              onClick={() => setSidebarCollapsed((c) => !c)}
              title={sidebarCollapsed ? "Expand sidebar" : "Collapse sidebar"}
            >
              {sidebarCollapsed ? "›" : "‹"}
            </button>
          </div>

          <nav className="sidebar-nav">
            <button type="button" className={`nav-item ${activeView === "dashboard" ? "active" : ""}`} onClick={() => setActiveView("dashboard")}>
              <IconHome size={18} /><span>Dashboard</span>
            </button>

            <button type="button" className={`nav-item ${activeView === "applications" ? "active" : ""}`} onClick={() => setActiveView("applications")}>
              <IconFileText size={18} /><span>Applications</span>
            </button>

            <button
              type="button"
              className={`nav-item ${activeView === "roadmap" ? "active" : ""}`}
              onClick={() => {
                if (applications.length > 0) openRoadmap(applications[0]);
                else setActiveView("roadmap");
              }}
            >
              <IconRoadmap size={18} /><span>Approval Roadmap</span>
            </button>

            <button type="button" className={`nav-item ${activeView === "ai-assistant" ? "active" : ""}`} onClick={() => setActiveView("ai-assistant")}>
              <IconBot size={18} /><span>AI Assistant</span>
            </button>

            <button type="button" className={`nav-item ${activeView === "documents" ? "active" : ""}`} onClick={() => setActiveView("documents")}>
              <IconFileCheck size={18} /><span>Documents</span>
            </button>

            <button type="button" className={`nav-item ${activeView === "delay-alerts" ? "active" : ""}`} onClick={() => setActiveView("delay-alerts")}>
              <IconClockAlert size={18} /><span>Delay Alerts</span>
            </button>

            <button type="button" className={`nav-item ${activeView === "compliance" ? "active" : ""}`} onClick={() => setActiveView("compliance")}>
              <IconRepeat size={18} /><span>Compliance</span>
            </button>

            <button type="button" className={`nav-item ${activeView === "schemes" ? "active" : ""}`} onClick={() => setActiveView("schemes")}>
              <IconAward size={18} /><span>Government Schemes</span>
            </button>

            <button type="button" className={`nav-item ${activeView === "notifications" ? "active" : ""}`} onClick={() => setActiveView("notifications")}>
              <IconBell size={18} /><span>Notifications</span>
              {unreadCount > 0 && (
                <span className="sidebar-count">{unreadCount}</span>
              )}
            </button>

            <button type="button" className={`nav-item ${activeView === "profile" ? "active" : ""}`} onClick={() => setActiveView("profile")}>
              <IconUser size={18} /><span>Profile</span>
            </button>
          </nav>

          {/* Helpline box */}
          {!sidebarCollapsed && (
            <div className="sidebar-helpline-box">
              <div className="helpline-header">
                <IconInfo size={16} />
                <strong>Investor Helpline</strong>
              </div>
              <span className="helpline-phone">1800 120 8040</span>
              <small>Mon - Sat (9:30 AM to 6:00 PM)</small>
            </div>
          )}

          {!sidebarCollapsed && (
            <div className="sidebar-footer-note">
              <span>UdyogFlow · Govt of Maharashtra</span>
            </div>
          )}
        </aside>

        {/* ── MAIN CONTENT ── */}
        <main className="portal-main-content">

          {/* ── PERSONALIZED HERO STRIP ── */}
          <div className="portal-hero-strip">
            <div className="hero-greeting-row">
              <span className="hero-eyebrow">
                UdyogFlow · Business Portal
              </span>
              <h1>
                {getGreeting()}, {displayName}
              </h1>
              <p className="hero-subline">
                Track your applications, statutory clearances, and compliance across Maharashtra in one place.
              </p>
              <div className="hero-user-meta-strip">
                <span className="hero-live-clock">
                  📅 {new Date().toLocaleDateString("en-IN", { weekday: "long", day: "numeric", month: "long", year: "numeric" })} &nbsp;·&nbsp; {clockStr}
                </span>
                <span className="meta-dot">·</span>
                <span className="hero-user-tag">
                  🏢 {user?.business_name || user?.businessName || "Registered Enterprise"}
                </span>
                <span className="meta-dot">·</span>
                <span className="hero-user-tag">
                  📍 {user?.district || "Maharashtra"}
                </span>
                {user?.user_id && (
                  <>
                    <span className="meta-dot">·</span>
                    <span className="hero-user-tag">
                      🆔 UID-{String(user.user_id).padStart(5, "0")}
                    </span>
                  </>
                )}
              </div>
            </div>
            <div className="hero-action-group">
              <button
                type="button"
                className="btn-create-app"
                onClick={() => setShowApplication(true)}
              >
                <IconPlus size={16} />
                <span>New Application</span>
              </button>
            </div>
          </div>

          {/* ================================================================
              VIEW: DASHBOARD (OVERVIEW)
             ================================================================ */}
          {activeView === "dashboard" && (
            <div className="overview-container">

              {/* 4 KPI Stat Cards — live data with count-up */}
              <section className="kpi-summary-row" ref={kpiRowRef}>
                <div className="stat-card stat-blue cursor-pointer" onClick={() => setActiveView("applications")}>
                  <div className="stat-icon-wrapper"><IconBuilding size={20} /></div>
                  <div className="stat-data">
                    <span className="stat-label">Total Applications</span>
                    <strong className="stat-number">
                      {loadingApplications ? "…" : String(displayedStats.total).padStart(2, "0")}
                    </strong>
                    <span className="stat-subtext">Registered in database</span>
                  </div>
                </div>

                <div className="stat-card stat-green">
                  <div className="stat-icon-wrapper"><IconCheck size={20} /></div>
                  <div className="stat-data">
                    <span className="stat-label">Approved</span>
                    <strong className="stat-number">
                      {loadingApplications ? "…" : String(displayedStats.approved).padStart(2, "0")}
                    </strong>
                    <span className="stat-subtext">Clearances issued</span>
                  </div>
                </div>

                <div className="stat-card stat-amber">
                  <div className="stat-icon-wrapper"><IconClockAlert size={20} /></div>
                  <div className="stat-data">
                    <span className="stat-label">In Progress</span>
                    <strong className="stat-number">
                      {loadingApplications ? "…" : String(displayedStats.inProgress).padStart(2, "0")}
                    </strong>
                    <span className="stat-subtext">Under department scrutiny</span>
                  </div>
                </div>

                <div className="stat-card stat-red">
                  <div className="stat-icon-wrapper"><IconAlertTriangle size={20} /></div>
                  <div className="stat-data">
                    <span className="stat-label">Action Required</span>
                    <strong className="stat-number">
                      {loadingApplications ? "…" : String(displayedStats.actionRequired).padStart(2, "0")}
                    </strong>
                    <span className="stat-subtext">Requires your attention</span>
                  </div>
                </div>
              </section>

              {/* Grid: Applications Table + Status Donut */}
              <section className="portal-grid-two fade-in-section">
                {/* Recent Applications Card */}
                <div className="portal-card applications-card">
                  <div className="card-header-bar">
                    <div className="header-titles">
                      <IconFileText size={18} />
                      <div>
                        <h2>Recent Applications</h2>
                        <p>Live applications saved in PostgreSQL</p>
                      </div>
                    </div>
                    <button type="button" className="link-btn" onClick={() => setActiveView("applications")}>
                      View All →
                    </button>
                  </div>

                  <div className="table-responsive">
                    <table className="gov-data-table">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Business &amp; Sector</th>
                          <th>Location</th>
                          <th>Status</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        {loadingApplications ? (
                          <tr>
                            <td colSpan="5" className="table-empty-cell">
                              <div className="table-spinner"></div>
                              <span>Loading applications…</span>
                            </td>
                          </tr>
                        ) : applications.length === 0 ? (
                          <tr>
                            <td colSpan="5" className="table-empty-cell">
                              <div className="table-empty-wrap">
                                <div className="table-empty-icon"><IconInfo size={24} /></div>
                                <p className="empty-title">No applications registered yet</p>
                                <p className="empty-desc">Get started by creating your enterprise application to generate a customized approval roadmap.</p>
                                <button
                                  type="button"
                                  className="btn-empty-start"
                                  onClick={() => setShowApplication(true)}
                                >
                                  <IconPlus size={14} />
                                  <span>Start New Application</span>
                                </button>
                              </div>
                            </td>
                          </tr>
                        ) : (
                          applications.slice(0, 4).map((app) => {
                            const status = app.status || "Draft";
                            const lower = status.toLowerCase();
                            let badgeClass = "badge-pending";
                            if (lower === "approved") badgeClass = "badge-completed";
                            else if (lower === "in progress" || lower === "in review" || lower === "under review") badgeClass = "badge-progress";
                            else if (lower === "action required" || lower === "rejected") badgeClass = "badge-danger";
                            return (
                              <tr key={app.application_id}>
                                <td><span className="app-code">#{app.application_id}</span></td>
                                <td>
                                  <div className="enterprise-cell">
                                    <strong>{app.business_name}</strong>
                                    <small>{app.industry}</small>
                                  </div>
                                </td>
                                <td><span className="location-tag">📍 {app.location}</span></td>
                                <td><span className={`status-pill ${badgeClass}`}>{status}</span></td>
                                <td>
                                  <button type="button" className="table-action-btn" onClick={() => openRoadmap(app)}>
                                    <span>Roadmap</span><IconArrowRight size={14} />
                                  </button>
                                </td>
                              </tr>
                            );
                          })
                        )}
                      </tbody>
                    </table>
                  </div>
                </div>

                {/* Status Donut Chart */}
                <div className="portal-card status-breakdown-card">
                  <div className="card-header-bar">
                    <div className="header-titles">
                      <IconShieldCheck size={18} />
                      <div>
                        <h2>Status Breakdown</h2>
                        <p>Current distribution of your filings</p>
                      </div>
                    </div>
                  </div>
                  <div className="chart-wrapper">
                    <div className="donut-circle" style={{ background: donutBackground }}>
                      <div className="donut-hole">
                        <strong className="donut-total">
                          {loadingApplications ? "…" : String(statistics.total).padStart(2, "0")}
                        </strong>
                        <span className="donut-caption">Total</span>
                      </div>
                    </div>
                    <div className="chart-legend-list">
                      <div className="legend-item">
                        <span className="legend-marker marker-green"></span>
                        <div className="legend-text"><span>Approved</span><strong>{statistics.approved}</strong></div>
                      </div>
                      <div className="legend-item">
                        <span className="legend-marker marker-amber"></span>
                        <div className="legend-text"><span>In Progress</span><strong>{statistics.inProgress}</strong></div>
                      </div>
                      <div className="legend-item">
                        <span className="legend-marker marker-red"></span>
                        <div className="legend-text"><span>Action Needed</span><strong>{statistics.actionRequired + statistics.rejected}</strong></div>
                      </div>
                      <div className="legend-item">
                        <span className="legend-marker marker-slate"></span>
                        <div className="legend-text"><span>Draft</span><strong>{statistics.draft}</strong></div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>

              {/* 8 Feature Shortcuts */}
              <section className="feature-highlights-section fade-in-section" ref={featureGridRef}>
                <div className="section-title-wrap">
                  <div className="title-left">
                    <h2>Platform Features</h2>
                    <p>Quick access to all industrial approval and compliance modules.</p>
                  </div>
                </div>

                <div className="feature-cards-grid">
                  <div className="feature-interactive-card" onClick={() => { if (applications.length > 0) openRoadmap(applications[0]); else setActiveView("roadmap"); }}>
                    <div className="card-icon-header icon-blue"><IconRoadmap size={20} /></div>
                    <h3>Approval Roadmap</h3>
                    <p>Track your step-by-step statutory clearances and SLA timelines.</p>
                    <span className="card-explore-link">Open Roadmap →</span>
                  </div>

                  <div className="feature-interactive-card" onClick={() => setActiveView("ai-assistant")}>
                    <div className="card-icon-header icon-purple"><IconBot size={20} /></div>
                    <h3>AI Assistant</h3>
                    <p>Get instant answers about clearances, MPCB categories, and policies.</p>
                    <span className="card-explore-link">Ask Assistant →</span>
                  </div>

                  <div className="feature-interactive-card" onClick={() => setActiveView("documents")}>
                    <div className="card-icon-header icon-green"><IconFileCheck size={20} /></div>
                    <h3>Documents</h3>
                    <p>Pre-validate file formats and reuse verified certificates securely.</p>
                    <span className="card-explore-link">Manage Documents →</span>
                  </div>

                  <div className="feature-interactive-card" onClick={() => setActiveView("delay-alerts")}>
                    <div className="card-icon-header icon-amber"><IconClockAlert size={20} /></div>
                    <h3>Delay Alerts</h3>
                    <p>Identify potential bottlenecks early to prevent project delays.</p>
                    <span className="card-explore-link">Check Alerts →</span>
                  </div>

                  <div className="feature-interactive-card" onClick={() => setActiveView("compliance")}>
                    <div className="card-icon-header icon-teal"><IconRepeat size={20} /></div>
                    <h3>Compliance</h3>
                    <p>Never miss annual license renewals, safety audits, and returns.</p>
                    <span className="card-explore-link">View Calendar →</span>
                  </div>

                  <div className="feature-interactive-card" onClick={() => setActiveView("schemes")}>
                    <div className="card-icon-header icon-orange"><IconAward size={20} /></div>
                    <h3>Government Schemes</h3>
                    <p>Explore subsidies and incentives under Package Scheme of Incentives.</p>
                    <span className="card-explore-link">View Schemes →</span>
                  </div>

                  <div className="feature-interactive-card" onClick={() => setActiveView("notifications")}>
                    <div className="card-icon-header icon-red"><IconBell size={20} /></div>
                    <h3>Notifications</h3>
                    <p>Real-time updates on application status and official circulars.</p>
                    <span className="card-explore-link">View Notifications →</span>
                  </div>

                  <div className="feature-interactive-card" onClick={() => setActiveView("profile")}>
                    <div className="card-icon-header icon-blue"><IconUser size={20} /></div>
                    <h3>Profile</h3>
                    <p>Manage your business entity profile and account settings.</p>
                    <span className="card-explore-link">View Profile →</span>
                  </div>
                </div>
              </section>
            </div>
          )}

          {/* ================================================================
              VIEW: APPLICATIONS (FULL TABLE)
             ================================================================ */}
          {activeView === "applications" && (
            <div className="module-view-container">
              <div className="module-header-banner">
                <h2>All Applications</h2>
                <p>Live industrial applications recorded in PostgreSQL database.</p>
              </div>

              <div className="card-controls mb-4">
                <div className="table-search-input">
                  <IconSearch size={14} />
                  <input
                    type="text"
                    placeholder="Search by name, sector…"
                    value={tableSearch}
                    onChange={(e) => setTableSearch(e.target.value)}
                  />
                </div>
                <select className="table-filter-select" value={tableStatusFilter} onChange={(e) => setTableStatusFilter(e.target.value)}>
                  <option value="all">All Statuses</option>
                  <option value="approved">Approved</option>
                  <option value="in-progress">In Progress</option>
                  <option value="action-required">Action Required</option>
                  <option value="draft">Draft</option>
                </select>
              </div>

              <div className="table-responsive">
                <table className="gov-data-table">
                  <thead>
                    <tr>
                      <th>Application ID</th>
                      <th>Enterprise</th>
                      <th>Sector</th>
                      <th>Location</th>
                      <th>Classification</th>
                      <th>Status</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {loadingApplications ? (
                      <tr>
                        <td colSpan="7" className="table-empty-cell">
                          <div className="table-spinner"></div>
                          <span>Loading applications…</span>
                        </td>
                      </tr>
                    ) : filteredApplications.length === 0 ? (
                      <tr>
                        <td colSpan="7" className="table-empty-cell">
                          <div className="table-empty-wrap">
                            <div className="table-empty-icon"><IconInfo size={24} /></div>
                            <p className="empty-title">No matching applications found</p>
                            <p className="empty-desc">No records match your active search or filter criteria. Try clearing your search term or adjusting filters.</p>
                          </div>
                        </td>
                      </tr>
                    ) : (
                      filteredApplications.map((app) => {
                        const status = app.status || "Draft";
                        const lower = status.toLowerCase();
                        let badgeClass = "badge-pending";
                        if (lower === "approved") badgeClass = "badge-completed";
                        else if (lower === "in progress" || lower === "in review" || lower === "under review") badgeClass = "badge-progress";
                        else if (lower === "action required" || lower === "rejected") badgeClass = "badge-danger";
                        return (
                          <tr key={app.application_id}>
                            <td><span className="app-code">APP-{String(app.application_id).padStart(4, "0")}</span></td>
                            <td><strong>{app.business_name}</strong></td>
                            <td>{app.industry}</td>
                            <td>📍 {app.location}</td>
                            <td>{app.business_type}</td>
                            <td><span className={`status-pill ${badgeClass}`}>{status}</span></td>
                            <td>
                              <button type="button" className="table-action-btn" onClick={() => openRoadmap(app)}>
                                <span>Roadmap</span><IconArrowRight size={14} />
                              </button>
                            </td>
                          </tr>
                        );
                      })
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* ================================================================
              VIEW: ROADMAP (SELECTOR — when accessed from sidebar without app)
             ================================================================ */}
          {activeView === "roadmap" && (
            <div className="module-view-container">
              <div className="module-header-banner">
                <h2>Approval Roadmap</h2>
                <p>Select an application to view its statutory approval journey.</p>
              </div>

              {applications.length > 0 ? (
                <div className="roadmap-select-list">
                  {applications.map((app) => (
                    <div key={app.application_id} className="app-select-card cursor-pointer" onClick={() => openRoadmap(app)}>
                      <div>
                        <h3>{app.business_name}</h3>
                        <p>{app.industry} · 📍 {app.location}</p>
                      </div>
                      <button type="button" className="btn-secondary">Open Roadmap →</button>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="empty-state-box">
                  <IconInfo size={24} />
                  <h3>No Applications Available</h3>
                  <p>Start your first application to generate a roadmap.</p>
                  <button type="button" className="btn-primary mt-3" onClick={() => setShowApplication(true)}>
                    Start New Application
                  </button>
                </div>
              )}
            </div>
          )}

          {/* ================================================================
              VIEW: AI ASSISTANT — Interactive Prototype
             ================================================================ */}
          {activeView === "ai-assistant" && (
            <div className="module-view-container">
              <div className="module-header-banner">
                <div className="module-tag prototype">AI ASSISTANT — PROTOTYPE</div>
                <h2>AI Assistant</h2>
                <p>
                  Guided help for industrial approvals, documents, departments, timelines, and government schemes.
                  Responses are based on built-in UdyogFlow knowledge — not a live AI model.
                </p>
              </div>

              {/* Disclaimer */}
              <div className="ai-assistant-disclaimer">
                <IconInfo size={14} />
                <span>
                  <strong>Note:</strong> This assistant uses rule-based responses contextual to your UdyogFlow data.
                  It does not connect to an external AI service. Always verify regulatory requirements with the relevant department.
                </span>
              </div>

              <div className="ai-chat-layout">
                {/* Chat window */}
                <div className="chat-window">
                  <div className="chat-messages">
                    {chatMessages.map((msg, i) => (
                      <div key={i} className={`chat-bubble ${msg.role}`}>
                        {msg.role === "bot" && (
                          <div className="bubble-avatar"><IconBot size={16} /></div>
                        )}
                        <div className="bubble-body">
                          {msg.text && (
                            <p dangerouslySetInnerHTML={{ __html: msg.text.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>") }} />
                          )}
                          {msg.list && msg.list.length > 0 && (
                            <ul className="chat-list">
                              {msg.list.map((item, j) => (
                                <li key={j}>{item}</li>
                              ))}
                            </ul>
                          )}
                          {msg.note && (
                            <p style={{ marginTop: "8px", fontSize: "11px", color: "var(--text-muted)", fontStyle: "italic" }}>
                              ℹ️ {msg.note}
                            </p>
                          )}
                          {/* Action button for roadmap/application */}
                          {msg.action === "roadmap" && (
                            <button
                              type="button"
                              className="ai-roadmap-action-btn"
                              onClick={() => {
                                if (applications.length > 0) openRoadmap(applications[0]);
                                else setActiveView("roadmap");
                              }}
                            >
                              <IconRoadmap size={13} /> View Approval Roadmap
                            </button>
                          )}
                          {msg.action === "application" && (
                            <button
                              type="button"
                              className="ai-roadmap-action-btn"
                              onClick={() => setShowApplication(true)}
                            >
                              <IconPlus size={13} /> Start New Application
                            </button>
                          )}
                        </div>
                      </div>
                    ))}

                    {/* Typing indicator */}
                    {isTyping && (
                      <div className="chat-bubble bot">
                        <div className="bubble-avatar"><IconBot size={16} /></div>
                        <div className="bubble-body">
                          <div className="ai-typing-indicator">
                            <div className="ai-typing-dot"></div>
                            <div className="ai-typing-dot"></div>
                            <div className="ai-typing-dot"></div>
                          </div>
                        </div>
                      </div>
                    )}
                    <div ref={chatEndRef} />
                  </div>

                  {/* Input row */}
                  <div className="chat-input-row">
                    <input
                      type="text"
                      placeholder="Type your question here…"
                      value={chatInput}
                      onChange={(e) => setChatInput(e.target.value)}
                      onKeyDown={(e) => { if (e.key === "Enter") handleChatSend(); }}
                    />
                    <button
                      type="button"
                      className="btn-chat-send"
                      onClick={handleChatSend}
                      disabled={isTyping}
                    >
                      Send →
                    </button>
                  </div>
                </div>

                {/* Info sidebar */}
                <div className="ai-info-sidebar">
                  <h4>Suggested Questions</h4>
                  <div className="suggested-questions-list">
                    {SUGGESTED_QUESTIONS.map((q) => (
                      <button
                        key={q}
                        type="button"
                        className="sugg-question-btn"
                        onClick={() => handleSuggestedQuestion(q)}
                        disabled={isTyping}
                      >
                        <span className="sugg-question-icon">›</span>
                        {q}
                      </button>
                    ))}
                  </div>

                  <h4>Quick Reference</h4>
                  <div className="kg-item">
                    <strong>MPCB Clearances</strong>
                    <p>Pollution categorized into Red, Orange, Green, and White based on industry type.</p>
                  </div>
                  <div className="kg-item">
                    <strong>Statutory SLAs</strong>
                    <p>Protected under Maharashtra Right to Public Services Act, 2015.</p>
                  </div>
                  <div className="kg-item">
                    <strong>MAITRI Portal</strong>
                    <p>Single Window for all Maharashtra industrial clearances — maitri.mahaonline.gov.in</p>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* ================================================================
              VIEW: DOCUMENTS (PROTOTYPE)
             ================================================================ */}
          {activeView === "documents" && (
            <DocumentPreValidation />
          )}

          {/* ================================================================
              VIEW: DELAY ALERTS (PROTOTYPE)
             ================================================================ */}
          {activeView === "delay-alerts" && (
            <div className="module-view-container">
              <div className="module-header-banner">
                <div className="module-tag prototype">PROTOTYPE PREVIEW</div>
                <h2>Delay Alerts</h2>
                <p>Monitor department turnaround times against statutory SLAs to avoid delays.</p>
              </div>

              <div className="radar-grid">
                <div className="radar-metric-card">
                  <span className="radar-eyebrow">DEPARTMENT MONITORING</span>
                  <h3>Maharashtra Pollution Control Board (MPCB)</h3>
                  <div className="radar-stat-line">
                    <span>SLA: <strong>45 Days</strong></span>
                    <span>Average: <strong>49 Days</strong></span>
                  </div>
                  <div className="sla-progress-bar">
                    <div className="sla-fill warning" style={{ width: "88%" }}></div>
                  </div>
                  <span className="radar-alert-note text-amber">
                    ⚠️ Site inspection backlog in Western Maharashtra. Ensure effluent diagrams are uploaded.
                  </span>
                </div>

                <div className="radar-metric-card">
                  <span className="radar-eyebrow">DEPARTMENT MONITORING</span>
                  <h3>MIDC Infrastructure Clearances</h3>
                  <div className="radar-stat-line">
                    <span>SLA: <strong>21 Days</strong></span>
                    <span>Average: <strong>14 Days</strong></span>
                  </div>
                  <div className="sla-progress-bar">
                    <div className="sla-fill success" style={{ width: "66%" }}></div>
                  </div>
                  <span className="radar-alert-note text-green">
                    ✅ Optimal performance. Processing 7 days ahead of statutory deadline.
                  </span>
                </div>

                <div className="radar-metric-card">
                  <span className="radar-eyebrow">DEPARTMENT MONITORING</span>
                  <h3>Directorate of Industrial Safety (DISH)</h3>
                  <div className="radar-stat-line">
                    <span>SLA: <strong>30 Days</strong></span>
                    <span>Average: <strong>28 Days</strong></span>
                  </div>
                  <div className="sla-progress-bar">
                    <div className="sla-fill success" style={{ width: "93%" }}></div>
                  </div>
                  <span className="radar-alert-note text-blue">
                    ℹ️ On track. Standard factory layout submitted.
                  </span>
                </div>
              </div>
            </div>
          )}

          {/* ================================================================
              VIEW: COMPLIANCE — Visual Calendar (ENHANCED)
             ================================================================ */}
          {activeView === "compliance" && (
            <div className="module-view-container">
              <div className="module-header-banner">
                <div className="module-tag prototype">PROTOTYPE PREVIEW</div>
                <h2>Compliance Calendar</h2>
                <p>
                  Track upcoming statutory renewal deadlines and environmental returns.
                  Dates shown are indicative; verify with the relevant department.
                </p>
              </div>

              <div className="compliance-layout">
                {/* Calendar Grid */}
                <div className="compliance-calendar-grid">
                  <div className="cal-header">
                    <button type="button" className="cal-nav-btn" onClick={prevCalMonth}>‹</button>
                    <h3>{MONTH_NAMES[calMonth]} {calYear}</h3>
                    <button type="button" className="cal-nav-btn" onClick={nextCalMonth}>›</button>
                  </div>

                  <div className="cal-weekdays">
                    {WEEKDAY_LABELS.map((d) => (
                      <div key={d} className="cal-weekday">{d}</div>
                    ))}
                  </div>

                  <div className="cal-days-grid">
                    {calDays.map((cell, idx) => {
                      if (cell.empty) {
                        return <div key={`e-${idx}`} className="cal-day empty"></div>;
                      }
                      return (
                        <div
                          key={cell.day}
                          className={`cal-day${cell.isToday ? " today" : ""}${cell.deadline ? " has-deadline" : ""}`}
                          title={cell.deadline ? cell.deadline.label : undefined}
                        >
                          {cell.day}
                          {cell.deadline && (
                            <div className={`deadline-dot ${cell.deadline.type}`}></div>
                          )}
                        </div>
                      );
                    })}
                  </div>

                  <div className="compliance-legend">
                    <div className="comp-legend-item">
                      <div className="comp-legend-dot" style={{ background: "var(--status-danger)" }}></div>
                      <span>Due Soon</span>
                    </div>
                    <div className="comp-legend-item">
                      <div className="comp-legend-dot" style={{ background: "var(--status-warning)" }}></div>
                      <span>Upcoming</span>
                    </div>
                    <div className="comp-legend-item">
                      <div className="comp-legend-dot" style={{ background: "var(--status-success)" }}></div>
                      <span>Scheduled</span>
                    </div>
                  </div>
                </div>

                {/* Upcoming Deadlines List */}
                <div className="upcoming-deadlines-card">
                  <h4>Upcoming Compliance Deadlines</h4>
                  <div className="comp-deadline-list">
                    <div className="comp-deadline-item">
                      <div className="comp-deadline-date-box urgent">
                        <strong>31</strong>
                        <span>MAR</span>
                      </div>
                      <div className="comp-deadline-body">
                        <strong>MPCB Annual Environmental Statement (Form V)</strong>
                        <small>Mandatory for Red and Orange category industries.</small>
                      </div>
                      <span className="comp-badge due">Due Soon</span>
                    </div>

                    <div className="comp-deadline-item">
                      <div className="comp-deadline-date-box upcoming">
                        <strong>30</strong>
                        <span>APR</span>
                      </div>
                      <div className="comp-deadline-body">
                        <strong>Factory License Renewal (DISH)</strong>
                        <small>Annual renewal under Maharashtra Factories Rules.</small>
                      </div>
                      <span className="comp-badge queued">Upcoming</span>
                    </div>

                    <div className="comp-deadline-item">
                      <div className="comp-deadline-date-box scheduled">
                        <strong>30</strong>
                        <span>JUN</span>
                      </div>
                      <div className="comp-deadline-body">
                        <strong>Annual Fire Safety Audit Report</strong>
                        <small>Form B submission to Maharashtra Fire Services.</small>
                      </div>
                      <span className="comp-badge queued">Scheduled</span>
                    </div>

                    <div className="comp-deadline-item">
                      <div className="comp-deadline-date-box scheduled">
                        <strong>30</strong>
                        <span>SEP</span>
                      </div>
                      <div className="comp-deadline-body">
                        <strong>MPCB Half-Yearly Return</strong>
                        <small>Effluent and emission data submission to MPCB.</small>
                      </div>
                      <span className="comp-badge queued">Scheduled</span>
                    </div>

                    <div className="comp-deadline-item">
                      <div className="comp-deadline-date-box upcoming">
                        <strong>31</strong>
                        <span>DEC</span>
                      </div>
                      <div className="comp-deadline-body">
                        <strong>Factory Annual Report Filing</strong>
                        <small>Annual return under Factories Act, 1948.</small>
                      </div>
                      <span className="comp-badge queued">Upcoming</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* ================================================================
              VIEW: GOVERNMENT SCHEMES (PROTOTYPE — unchanged)
             ================================================================ */}
          {activeView === "schemes" && (
            <div className="module-view-container">
              <div className="module-header-banner">
                <div className="module-tag prototype">PROTOTYPE PREVIEW</div>
                <h2>Government Schemes &amp; Incentives</h2>
                <p>Explore fiscal incentives and subsidies under the Maharashtra Industrial Policy.</p>
              </div>

              <div className="schemes-grid">
                <div className="scheme-card highlighted">
                  <div className="scheme-badge">FLAGSHIP</div>
                  <h3>Package Scheme of Incentives (PSI 2019)</h3>
                  <p>Incentives for industrial dispersal into developing talukas (B, C, D, D+).</p>
                  <ul className="scheme-benefits">
                    <li>Industrial Promotion Subsidy up to 100% of Fixed Capital Investment</li>
                    <li>5% Interest Subsidy on term loans for MSMEs</li>
                    <li>Electricity duty exemption for up to 10 years</li>
                  </ul>
                  <button type="button" className="btn-scheme-apply">Check Eligibility →</button>
                </div>

                <div className="scheme-card">
                  <div className="scheme-badge">INNOVATION</div>
                  <h3>MSInS Startup Patent Subsidy</h3>
                  <p>Financial support up to ₹15 Lakhs for patents and quality certifications.</p>
                  <ul className="scheme-benefits">
                    <li>Patent filing reimbursement up to ₹2 Lakhs</li>
                    <li>Quality testing fee reimbursement</li>
                  </ul>
                  <button type="button" className="btn-scheme-apply secondary">View Details →</button>
                </div>

                <div className="scheme-card">
                  <div className="scheme-badge">GREEN ENERGY</div>
                  <h3>Clean Energy Industrial Transition</h3>
                  <p>Subsidies for rooftop solar installation and effluent treatment.</p>
                  <ul className="scheme-benefits">
                    <li>25% capital subsidy on effluent treatment equipment</li>
                    <li>Priority net-metering approval</li>
                  </ul>
                  <button type="button" className="btn-scheme-apply secondary">View Details →</button>
                </div>
              </div>
            </div>
          )}

          {/* ================================================================
              VIEW: NOTIFICATIONS — Read/Unread Interaction (ENHANCED)
             ================================================================ */}
          {activeView === "notifications" && (
            <div className="module-view-container">
              <div className="module-header-banner">
                <div className="module-tag prototype">PROTOTYPE PREVIEW</div>
                <h2>Notifications &amp; Circulars</h2>
                <p>Official alerts issued by the Department of Industries and MAITRI.</p>
              </div>

              <div className="notifications-header-bar">
                <h3>
                  All Notifications
                  {unreadCount > 0 && (
                    <span className="notif-count-chip">{unreadCount}</span>
                  )}
                </h3>
                {unreadCount > 0 && (
                  <button type="button" className="mark-all-read-btn" onClick={markAllRead}>
                    Mark all as read
                  </button>
                )}
              </div>

              <div className="alerts-full-list">
                {notifications.map((notif) => (
                  <div
                    key={notif.id}
                    className={`alert-full-item ${notif.type}${notif.read ? " read" : ""}`}
                    onClick={() => toggleNotifRead(notif.id)}
                    title={notif.read ? "Click to mark as unread" : "Click to mark as read"}
                  >
                    <div className="alert-unread-dot"></div>
                    <div className="alert-left-icon">{notif.icon}</div>
                    <div className="alert-content">
                      <div className="alert-title-row">
                        <strong>{notif.title}</strong>
                        <span className="alert-time">{notif.time}</span>
                      </div>
                      <p>{notif.body}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* ================================================================
              VIEW: PROFILE — Real user data (ENHANCED)
             ================================================================ */}
          {activeView === "profile" && (
            <div className="module-view-container">
              <div className="module-header-banner">
                <h2>Investor Profile</h2>
                <p>Your registered business profile under Government of Maharashtra Single Window.</p>
              </div>

              <div className="profile-details-card">
                <div className="profile-header-row">
                  <div className="profile-avatar-initials">{userInitial}</div>
                  <div className="profile-name-col">
                    <h3>{displayName}</h3>
                    <div className="profile-role-tag">
                      Industrial Unit Account
                      <span className="profile-verified-chip">✓ Verified</span>
                    </div>
                  </div>
                </div>

                <div className="profile-info-grid">
                  <div className="profile-field">
                    <label>Account Type</label>
                    <strong>Business Investor (MAITRI Single Window)</strong>
                  </div>
                  <div className="profile-field">
                    <label>Email Address</label>
                    <strong>{userEmail}</strong>
                  </div>
                  <div className="profile-field">
                    <label>User ID</label>
                    <strong style={{ fontFamily: "var(--font-mono)", fontSize: "12px" }}>
                      {user?.user_id ? `UID-${String(user.user_id).padStart(6, "0")}` : "—"}
                    </strong>
                  </div>
                  <div className="profile-field">
                    <label>Jurisdiction</label>
                    <strong>State of Maharashtra (All 36 Districts)</strong>
                  </div>
                  <div className="profile-field">
                    <label>Registered Submissions</label>
                    <strong>{applications.length} Application{applications.length !== 1 ? "s" : ""} on File</strong>
                  </div>
                  <div className="profile-field">
                    <label>Portal Access</label>
                    <strong>MAITRI Single Window — Full Access</strong>
                  </div>
                </div>

                <div className="profile-actions-row">
                  <button
                    type="button"
                    className="btn-secondary"
                    onClick={() => alert("Profile update form will open in account management.")}
                  >
                    Edit Profile
                  </button>
                  <button
                    type="button"
                    className="btn-secondary"
                    onClick={() => alert("Password reset link will be sent to your email.")}
                  >
                    Change Password
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* Portal Footer */}
          <footer className="portal-footer">
            <span className="footer-copy">
              © 2026 Government of Maharashtra · UdyogFlow Platform
            </span>
            <div className="footer-links">
              <a href="#maitri" onClick={(e) => { e.preventDefault(); setActiveView("dashboard"); }}>Dashboard</a>
              <a href="#help" onClick={(e) => { e.preventDefault(); setActiveView("ai-assistant"); }}>AI Assistant</a>
              <a href="#notif" onClick={(e) => { e.preventDefault(); setActiveView("notifications"); }}>Notifications</a>
            </div>
          </footer>
        </main>
      </div>
    </div>
  );
}

export default BusinessDashboard;